# Welcome to Jekyll!
title: Lebenslauf Michael Höflmaier
url:
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: de                    # html lang en
open: true                  # open or close your site
date_format: "%d-%m-%Y"     # date format
google_analytics:           # your google analytics
theme_color: "#f21d1d"      # your favorite theme color
